name: 'Block fixup commit merge'
description: 'Block merge of PRs containing fixup, squash, and merge commits.'
author: 'Brad Erickson, updated for Gastronomous Technologies by Jackson Brown'
runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  icon: 'scissors'
  color: 'orange'
